import './globals.css';
import { Theme } from '@radix-ui/themes';
import { Inter } from 'next/font/google';
import Link from 'next/link';

import type { Metadata } from 'next';

import '@radix-ui/themes/styles.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <header>
            <Link href="/">a</Link>
          </header>
          {children}
        </Theme>
      </body>
    </html>
  );
}
